### ISSUE TITLE
Getting nan on cuda

### ISSUE THREAD

**Issue by fangzhangmnm** [wangleiphy/tensorgrad#4]
The ising example
cuda with fp32:
lnZ: 0.8793611526489258 diff: -3.0416669583108143e-06
dlnZ: nan diff: nan
dlnZ2: nan diff: nan

cuda with fp64:
lnZ: 0.8793630603068638 diff: -8.647900870359195e-07
dlnZ: nan diff: nan
dlnZ2: nan diff: nan

cpu with fp32:
lnZ: 0.8793631196022034 diff: -8.048757504595195e-07
dlnZ: 1.1060452461242676 diff: -3.073004790032506e-05
dlnZ2: nan diff: nan

cpu with fp64:
lnZ: 0.879363060306853 diff: -8.647900994087115e-07
dlnZ: 1.1060454076032784 diff: -3.055490180757121e-05
dlnZ2: 5.384045897129937 diff: -0.00029130064828685555

Best,

**Comment by XingyuZhang2018** [comment]
Thanks for this commention and two way to sovle:

1.  be sure to use pytorch 1.3.1 + cuda 10.1
2.  less `Niter` -- new version the cuda-pytorch seems to be less stable for backpropagation.
